plugins {
    id 'com.android.application'
}

android {
    namespace 'com.asmontec.bydavm.car'
    compileSdk 35

    defaultConfig {
        applicationId 'com.asmontec.bydavm.car'
        minSdk 23
        targetSdk 34
        versionCode 7
        versionName '1.0.0'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            debuggable false
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError true
        checkReleaseBuilds true
        disable 'ExpiredTargetSdkVersion'
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
