plugins {
    id 'com.android.application'
}

android {
    namespace 'com.asmontec.bydavm.car'
    compileSdk 35

    defaultConfig {
        applicationId 'com.asmontec.bydavm.car'
        minSdk 23
        targetSdk 34
        versionCode 7
        versionName '0.7.0-background-mqtt'
    }

    buildTypes {
        debug { debuggable true }
        release {
            debuggable false
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lint {
        abortOnError true
        checkReleaseBuilds true
    }
}
